[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tgi_profiler"
version = "0.1.0"
dependencies = [
    "docker",
    "requests"
]

[project.optional-dependencies]
test = [
    "pytest"
]